#!/usr/bin/env python3
"""Generate complete roots dict for all 306 words. Run this first, then process."""
import json, re

with open('/home/Lu/gre_batch_8_raw.json') as f:
    data = json.load(f)

# Build comprehensive ROOTS dict - all 306 entries
# Format: "name": "root-breakdown → meaning",
# Many already exist in process_batch8.py; these are the missing ones
additional_roots = {
    'self-abasement': 'self-自己 + abase-贬低 + ment → 自卑、自谦',
    'self-absorbed': 'self-自己 + absorb-吸收 + ed → 自恋的、自私的',
    'sensation': 'sens-感觉 + ation → 感觉、知觉',
    'sensitive': 'sens-感觉 + itive → 敏感的',
    'sentinel': 'sent-感觉 + inel → 哨兵（警觉者）',
    'septic': 'sept-腐烂 + ic → 腐败的、感染的',
    'sepulchral': 'sepulch-坟墓 + ral → 阴沉的、丧葬的',
    'sequela': 'sequ-跟随 + ela → 结果、后遗症',
    'sere': 'sere-干枯 → 干枯的、凋萎的',
    'sermon': 'serm-讲话 + on → 布道、说教',
    'serrate': 'serr-锯齿 + ate → 锯齿状的',
    'serried': 'serr-锯齿 + ied → 密集的（如锯齿般紧密排列）',
    'severe': 'sever-严厉 + e → 严厉的、严重的',
    'shackle': 'shackle-脚镣 → 束缚、枷锁',
    'shadow': 'shadow-影子 → 偷偷尾随',
    'shallow': 'shallow-浅 → 浅显的、浅薄的',
    'sham': 'sham-假装 → 欺瞒、假冒',
    'shiftless': 'shift-改变 + less-无 → 胸无大志的、懒惰的',
    'shipshape': 'ship-船 + shape-形状 → 井然有序的（船上的整洁状态）',
    'shoal': 'shoal-浅 → 浅的；鱼群',
    'shopworn': 'shop-商店 + worn-磨损 → 陈旧的、过时的',
    'shred': 'shred-碎片 → 少量、碎条',
    'shrink': 'shrink-收缩 → 缩小、减少',
    'shroud': 'shroud-裹尸布 → 隐蔽物、覆盖',
    'shrug': 'shrug-耸肩 → 轻视、忽略',
    'sidestep': 'side-旁边 + step-步 → 回避、侧步躲避',
    'signal': 'sign-标记 + al → 显著的、非同寻常的',
    'simpleton': 'simple-简单 + ton-人 → 笨蛋、头脑简单者',
    'sin': 'sin-罪 → 罪恶的事',
    'sincere': 'sin-无 + cere-蜡 → 真诚的（无蜡的、不掩饰的）',
    'sinew': 'sinew-肌腱 → 活力、力量',
    'singe': 'singe-烧焦 → 轻微烧焦',
    'sip': 'sip-小口喝 → 啜饮',
    'skeleton': 'skeleton-骨架 → 框架、梗概',
    'skirmish': 'skirmish-小冲突 → 小规模战斗',
    'slake': 'slake-缓和 → 使满足、解渴',
    'slant': 'slant-倾斜 → 角度、偏向性的看法',
    'slew': 'slew-大量 → 许多、大量',
    'slight': 'slight-轻微 → 不重要的、纤细的',
    'sling': 'sling-投掷 → 投掷、扔',
    'slippery': 'slip-滑 + pery → 光滑的、不可靠的',
    'slipshod': 'slip-滑 + shod-穿鞋 → 粗心的、不严谨的',
    'sloppy': 'slop-溅出 + py → 邋遢的、马虎的',
    'sloth': 'sloth-懒惰 → 怠惰、懒散',
    'slouch': 'slouch-没精打采 → 懒人、低头垂肩',
    'slovenly': 'sloven-邋遢鬼 + ly → 邋遢的、不修边幅的',
    'sluggard': 'slugg-缓慢 + ard-人 → 懒人、怠惰者',
    'slur': 'slur-含糊 → 耻辱（含糊不清的指责）',
    'sly': 'sly-狡猾 → 狡猾的、诡秘的',
    'smarmy': 'smarm-讨好 + y → 虚情假意的、谄媚的',
    'smart': 'smart-锐利 → 聪颖的、反应敏捷的',
    'smattering': 'smatter-一知半解 + ing → 浅薄的知识',
    'smuggling': 'smuggle-走私 + ing → 走私、私运',
    'snarl': 'snarl-纠缠 → 纠结、混乱',
    'sneer': 'sneer-嘲笑 → 轻蔑地嘲笑',
    'snobbish': 'snob-势利 + bish → 谄上傲下的、自大的',
    'sodden': 'sod-浸泡 + en → 湿透的',
    'solace': 'sol-安慰 + ace → 安慰、慰藉',
    'solder': 'solder-焊接 → 连接、联合',
    'solemnity': 'solemn-庄严 + ity → 严肃、庄严',
    'solid': 'solid-坚固 → 固态的、坚固的、可靠的',
    'soliloquy': 'sol-独自 + loqu-说 + y → 独白、自言自语',
    'solitude': 'sol-独自 + itude → 孤独、独居',
    'solvent': 'solv-解决 + ent → 有偿付能力的；溶剂',
    'somatic': 'somat-身体 + ic → 肉体的、身体的',
    'somber': 'som-暗 + ber → 昏暗的、忧郁的',
    'somnolence': 'somn-睡眠 + olence → 瞌睡、嗜睡',
    'sonnet': 'son-声音 + net → 十四行诗',
    'sop': 'sop-浸泡 → 安慰物（用来讨好人的东西）',
    'sophism': 'soph-智慧 + ism → 诡辩（看似聪明实则谬误）',
    'sound': 'sound-健全 → 牢固的、健康的、合理的',
    'spat': 'spat-轻拍 → 小争吵',
    'spate': 'spate-洪水 → 突发的洪水；大量',
    'specific': 'spec-看 + ific → 特有的、具体的',
    'speck': 'speck-斑点 → 小点、少量',
    'spectator': 'spect-看 + ator-人 → 旁观者、观众',
    'speculate': 'spec-看 + ulate → 推测、投机',
    'spent': 'spend-花费 + t → 精疲力竭的、用尽的',
    'spindly': 'spindle-纺锤 + y → 细长纤弱的',
    'spiny': 'spin-刺 + y → 多刺的、棘手的',
    'spleen': 'spleen-脾脏（传统认为与怒气相关）→ 怒气、怨恨',
    'spoof': 'spoof-恶搞 → 轻松模仿、戏谑',
    'sprawl': 'sprawl-伸展 → 杂乱无序地扩展',
    'spurn': 'spurn-踢开 → 摈弃、拒绝',
    'squabble': 'squabble-争吵 → 口角、小争吵',
    'squall': 'squall-尖叫 → 暴风；大声哭喊',
    'squander': 'squander-分散 → 挥霍、浪费',
    'squat': 'squat-蹲 → 矮胖的、蹲着的',
    'squelch': 'squelch-压碎 → 压制、镇压',
    'squint': 'squint-斜视 → 斜视、眯眼看',
    'stabilize': 'stabil-稳定 + ize → 使稳定',
    'stammer': 'stammer-口吃 → 结巴、口吃',
    'startle': 'start-惊起 + le → 使吓一跳',
    'stature': 'stat-站立 + ure → 身高、声望',
    'stealth': 'stealth-秘密 → 秘密行动、隐秘',
    'stench': 'stench-恶臭 → 臭气',
    'stentorian': 'Stentor-（希腊传令官）+ ian → 声音洪亮的',
    'stickler': 'stick-坚持 + ler-人 → 坚持细节者、一丝不苟的人',
    'stiff': 'stiff-僵硬 → 僵硬的、生硬的',
    'stingy': 'sting-刺 + y → 吝啬的（像被刺一样小气）',
    'stipple': 'stippl-点 + e → 点刻、画点',
    'stitch': 'stitch-针脚 → 突然剧痛（像被针刺）',
    'stockade': 'stock-木桩 + ade → 栅栏、围栏',
    'stoic': 'Stoic-斯多葛学派 → 隐忍的、冷静的',
    'stoke': 'stoke-添柴 → 添加燃料、煽动',
    'stomach': 'stomach-胃 → 容忍、忍受',
    'stonewall': 'stone-石头 + wall-墙 → 拒绝合作、阻挠',
    'stouthearted': 'stout-结实 + heart-心 + ed → 勇敢的、刚毅的',
    'strait': 'strait-狭窄 → 海峡；困境',
    'strand': 'strand-线 → 一股、一缕；使搁浅',
    'stratagem': 'strata-策略 + gem → 谋略、策略',
    'stray': 'stray-偏离 → 走失的、漫无目的的',
    'strength': 'strength-力量 → 力量、优势',
    'striate': 'stri-条纹 + ate → 加条纹、有纹路',
    'stricture': 'strict-严格 + ure → 苛评、责难；约束',
    'strident': 'strid-刺耳 + ent → 刺耳的、尖锐的',
    'strike': 'strike-打 → 罢工；攻击；突然想到',
    'strip': 'strip-剥夺 → 脱衣、剥去、剥夺',
    'studio': 'stud-学习 + io → 工作室、画室',
    'stupor': 'stup-麻木 + or → 迟钝、昏迷',
    'sturdy': 'sturdy-结实 → 强健的、结实的',
    'stygian': 'Styx-冥河 + ian → 极黑暗的、地狱般的',
    'subject': 'sub-下 + ject-投 → 臣民；主题；使遭受',
    'subjugate': 'sub-下 + jug-轭 + ate → 征服、镇压',
    'subliminal': 'sub-下 + limin-门槛 + al → 下意识的、潜意识的',
    'subservient': 'sub-下 + serv-服务 + ient → 屈从的、奉承的',
    'subside': 'sub-下 + sid-坐 + e → 下陷、消退、平息',
    'subsidiary': 'sub-下 + sid-坐 + iary → 辅助的、次要的',
    'subsidy': 'sub-下 + sid-坐 + y → 补助金（从下支持）',
    'substantive': 'sub-下 + stant-站立 + ive → 实质的、独立存在的',
    'subvert': 'sub-下 + vert-转 → 颠覆、暗中破坏',
    'succor': 'suc-下 + cor-跑 → 救援、援助',
    'suffuse': 'suf-下 + fus-流 + e → 弥漫、充满',
    'sulk': 'sulk-愠怒 → 生气、闷闷不乐',
    'summary': 'summ-总和 + ary → 摘要、概要',
    'summit': 'summ-最高 + it → 顶点、峰会',
    'summon': 'sum-下 + mon-提醒 → 召集、召唤',
    'superimpose': 'super-上 + impose-强加 → 叠加、添加上去',
    'supposition': 'sup-下 + posit-放 + ion → 假定、推测',
    'suppress': 'sup-下 + press-压 → 压制、抑制',
    'surcharge': 'sur-上 + charge-收费 → 过高收费、附加费',
    'surfeit': 'sur-上 + feit-做 → 过量、饮食过度',
    'surrender': 'sur-上 + render-交出 → 投降、放弃',
    'susceptibility': 'sus-下 + cept-拿 + ibility → 易感性、敏感性',
    'suspend': 'sus-下 + pend-挂 → 暂停、悬挂',
    'suture': 'sut-缝 + ure → 缝合、缝线',
    'svelte': 'svelte-苗条 → (女子)苗条优雅的',
    'swagger': 'swagger-大摇大摆 → 趾高气昂地走',
    'swear': 'swear-发誓 → 咒骂；宣誓',
    'sweltering': 'swelter-闷热 + ing → 酷热的',
    'swill': 'swill-冲洗 → 痛饮、大口吃喝',
    'sybarite': 'Sybaris-（古希腊奢侈城市）→ 奢侈逸乐者',
    'syllabus': 'syl-共同 + lab-拿 + us → 提纲、摘要',
    'syllogism': 'syl-共同 + log-推理 + ism → 三段论、演绎推理',
    'symmetry': 'sym-共同 + metr-测量 + y → 对称、匀称',
    'synchronous': 'syn-共同 + chron-时间 + ous → 同时的、同步的',
    'shrink': 'shrink-收缩 → 缩小、退缩',
}

# Now apply: read existing roots from process_batch8.py, merge, write updated
with open('/home/Lu/process_batch8.py', 'r') as f:
    content = f.read()

# Check current roots count
import re
matches = re.findall(r"'([a-z-]+)':\s+'([^']+)'", content)
existing_roots = {m[0]: m[1] for m in matches}
print(f"Existing roots: {len(existing_roots)}")
print(f"Additional roots: {len(additional_roots)}")

# Find what's still missing
all_names = [d['name'].lower() for d in data]
missing = [n for n in all_names if n not in existing_roots and n not in additional_roots]
print(f"Still missing: {len(missing)}")
for m in missing:
    print(f"  {m}")
